## Assisted Practice 1 - Data Exploration Part - a

### Importing and Storing data

**Problem Statement:**
    * Extract data from the given SalaryGender CSV file
    * store the data from each column in a separate NumPy array



In [1]:
#importing libraries

import numpy as np
import pandas as pd

In [2]:
#importing data 
#reading csv file into dataframe

df = pd.read_csv("C:\\Users\\DELL\\Desktop\\Machine-Learning\\Lesson-1-Data Preprocessing\\Assisted Practice Datasets\\SalaryGender.csv",delimiter=',')

In [3]:
#first 5 obs of data
df.head(5)

Salary  Gender  Age  PhD
0   140.0       1   47    1
1    30.0       0   65    1
2    35.1       0   56    0
3    30.0       1   23    0
4    80.0       0   53    1

In [4]:
print(df)      #printing the dataframe

    Salary  Gender  Age  PhD
0   140.00       1   47    1
1    30.00       0   65    1
2    35.10       0   56    0
3    30.00       1   23    0
4    80.00       0   53    1
5    30.00       0   27    0
6    60.00       1   53    0
7    31.10       0   30    0
8   125.00       1   44    1
9    51.00       1   63    1
10    3.00       1   22    0
11   46.00       1   59    0
12  150.00       1   60    1
13    3.00       1   28    0
14  130.00       1   65    0
15   15.00       0   25    0
16  130.00       1   65    0
17   84.00       0   47    1
18  190.00       1   66    1
19   74.00       1   45    1
20   73.00       0   46    0
21   10.00       0   24    0
22   50.00       0   60    0
23    7.00       0   63    0
24    9.50       0   27    0
25   15.20       1   66    1
26   28.60       1   36    1
27   20.00       0   30    0
28   72.00       0   51    1
29   81.00       1   65    1
..     ...     ...  ...  ...
70   40.70       0   57    0
71   15.00       1   23    0
72    0.25    

In [5]:
#creating numpy array out of each column of the dataframe

Salary = np.array(df['Salary'])
Gender = np.array(df['Gender'])
Age = np.array(df['Age'])
PhD = np.array(df['PhD'])

In [6]:
Salary

array([140.  ,  30.  ,  35.1 ,  30.  ,  80.  ,  30.  ,  60.  ,  31.1 ,
       125.  ,  51.  ,   3.  ,  46.  , 150.  ,   3.  , 130.  ,  15.  ,
       130.  ,  84.  , 190.  ,  74.  ,  73.  ,  10.  ,  50.  ,   7.  ,
         9.5 ,  15.2 ,  28.6 ,  20.  ,  72.  ,  81.  , 100.  ,  90.  ,
        90.  ,  35.  ,  30.  ,  25.  ,  52.  ,   9.  ,  63.  ,  72.  ,
        16.  ,  92.  , 106.  ,   2.5 ,   9.  ,  32.  ,  32.  ,  55.  ,
        52.  ,  28.  ,  20.  ,  14.7 ,  22.3 ,  34.8 ,  84.  ,  19.  ,
       160.  ,  65.  ,  55.  ,   4.6 , 102.  ,  20.  ,  62.  ,  55.  ,
        45.6 ,  40.  ,  24.  ,  35.  ,  48.  ,  20.  ,  40.7 ,  15.  ,
         0.25, 152.  ,  39.8 ,  12.  ,  30.  , 120.  ,   1.7 ,  36.  ,
        96.  ,  38.  ,  90.  ,   9.  ,  25.8 ,  22.  ,  38.8 ,  72.  ,
        89.  ,  41.  ,  89.  ,  25.  ,  52.  , 115.  ,  66.  ,  18.6 ,
       152.  ,   1.8 ,  35.  ,   4.  ])

In [7]:
Gender

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0], dtype=int64)

In [8]:
Age

array([47, 65, 56, 23, 53, 27, 53, 30, 44, 63, 22, 59, 60, 28, 65, 25, 65,
       47, 66, 45, 46, 24, 60, 63, 27, 66, 36, 30, 51, 65, 45, 52, 54, 30,
       52, 26, 49, 22, 34, 60, 28, 58, 77, 67, 27, 48, 45, 49, 36, 65, 32,
       49, 67, 22, 49, 43, 61, 43, 52, 51, 66, 29, 62, 56, 61, 56, 41, 24,
       60, 43, 57, 23, 53, 71, 20, 27, 69, 58, 37, 32, 33, 32, 60, 71, 30,
       62, 54, 42, 62, 51, 71, 29, 55, 54, 55, 26, 56, 28, 44, 24],
      dtype=int64)

In [9]:
PhD

array([1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

## Done!